#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
LibSurgeon Test Suite - Shared Fixtures

This module contains shared pytest fixtures used across all test modules.
"""

import os
import shutil
import subprocess
import sys
import tempfile

import pytest

# Add parent directory to path for imports
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


# ============================================================
# Fixtures
# ============================================================


@pytest.fixture
def temp_dir():
    """Create a temporary directory for tests"""
    tmp = tempfile.mkdtemp(prefix="libsurgeon_test_")
    yield tmp
    shutil.rmtree(tmp, ignore_errors=True)


@pytest.fixture
def sample_cpp_file(temp_dir):
    """Create a sample decompiled C++ file"""
    content = """/**
 * Auto-generated decompiled code from: TestModule.o
 * Generated by LibSurgeon (Ghidra-based decompiler)
 */

#include <stdint.h>
#include <stdbool.h>

namespace xxgfx {

// ============================================================
// Class: TestClass
// ============================================================

// Function: testFunction

void __thiscall TestClass::testFunction(TestClass *this, int param_1)
{
    undefined4 local_10;
    local_10 = *(undefined4 *)(this + 8);
    if (param_1 == 0) {
        __assert_fail("param != 0", "framework/source/test.cpp", 42, "void test()");
    }
    return;
}

// Function: anotherFunction

int TestClass::anotherFunction(void)
{
    return *(int *)(this + 0x10);
}

} // namespace xxgfx
"""
    filepath = os.path.join(temp_dir, "TestModule.cpp")
    with open(filepath, "w") as f:
        f.write(content)
    return filepath


@pytest.fixture
def sample_bad_cpp_file(temp_dir):
    """Create a sample decompiled file with quality issues"""
    content = """/**
 * Auto-generated with issues
 */

void bad_function(void)
{
    halt_baddata();
    halt_baddata();
    undefined4 local_10;
    undefined8 local_20;
    undefined local_30;
    goto LAB_001234;
LAB_001234:
    return;
}
"""
    filepath = os.path.join(temp_dir, "BadModule.cpp")
    with open(filepath, "w") as f:
        f.write(content)
    return filepath


@pytest.fixture
def sample_c_file(temp_dir):
    """Create a sample decompiled C file (not C++)"""
    content = """/**
 * Auto-generated decompiled C code
 * Generated by LibSurgeon
 */

#include <stdint.h>

// Function: simple_c_function

int simple_c_function(int param)
{
    int result = param * 2;
    return result;
}

// Function: another_c_function

void another_c_function(void)
{
    return;
}
"""
    filepath = os.path.join(temp_dir, "c_module.c")
    with open(filepath, "w") as f:
        f.write(content)
    return filepath


@pytest.fixture
def test_archive(temp_dir):
    """Create a minimal test archive if ar is available"""
    # Create a simple C file
    c_file = os.path.join(temp_dir, "test.c")
    with open(c_file, "w") as f:
        f.write("int test_func(void) { return 42; }\n")

    # Compile to object file
    o_file = os.path.join(temp_dir, "test.o")
    try:
        subprocess.run(
            ["gcc", "-c", c_file, "-o", o_file], check=True, capture_output=True
        )
    except (subprocess.CalledProcessError, FileNotFoundError):
        pytest.skip("gcc not available")

    # Create archive
    a_file = os.path.join(temp_dir, "libtest.a")
    try:
        subprocess.run(["ar", "rcs", a_file, o_file], check=True, capture_output=True)
    except (subprocess.CalledProcessError, FileNotFoundError):
        pytest.skip("ar not available")

    return a_file
